
name: ✨ Feature request
about: Suggest a new feature or improvement
title: "[FEATURE] - "
labels: enhancement
assignees: ''

body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: What do you want to add or improve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Benefits
      description: Why is this feature valuable?
    validations:
      required: true
